site_name: 未完成的八拍

repo_name: LEMON
repo_url: https://miaolianlemon.github.io/lemon/

theme:
  name: 'material'
  features:
    - header.autohide
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: 切换到暗色
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: 切换到明色

nav:
  - 嗨~: index.md

  - 读感:
      嫌疑人X的献身: 读感/嫌疑人X的献身.md
      白鸟与蝙蝠: 读感/白鸟与蝙蝠.md
      恶意: 读感/恶意.md
  - 盗作:
      Sea and Sand: 盗作/Sea and Sand.md
      With You: 盗作/With You.md
  - 言葉: 言葉/言葉.md





